package com.oracle.xmlns.oxp.service.publicreportservice;

import javax.xml.ws.WebServiceRef;

import weblogic.wsee.jws.jaxws.owsm.SecurityPoliciesFeature;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

public class ExternalReportWSSServiceClient
{
  @WebServiceRef
  private static ExternalReportWSSService_Service externalReportWSSService_Service;

  public static void main(String [] args)
  {
    externalReportWSSService_Service = new ExternalReportWSSService_Service();
        SecurityPoliciesFeature securityFeatures =
            new SecurityPoliciesFeature(new String[] { "oracle/wss_saml_token_bearer_over_ssl_client_policy" });
        ExternalReportWSSService externalReportWSSService = externalReportWSSService_Service.getExternalReportWSSService(securityFeatures);
        // Add your code to call the desired methods.
  }
}
