package com.oracle.xmlns.oxp.service.publicreportservice;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

@WebService(wsdlLocation="https://eehx-test.bi.em3.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?WSDL",
  targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
  name="ExternalReportWSSService")
@XmlSeeAlso(
  { com.oracle.xmlns.oxp.service.publicreportservice.ObjectFactory.class })
public interface ExternalReportWSSService
{
  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getSecurityModelRequest",
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getSecurityModelResponse")
  @ResponseWrapper(localName="getSecurityModelResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetSecurityModelResponse")
  @RequestWrapper(localName="getSecurityModel", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetSecurityModel")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getSecurityModelReturn")
  public String getSecurityModel();

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getBIPHTTPSessionIntervalRequest",
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getBIPHTTPSessionIntervalResponse")
  @ResponseWrapper(localName="getBIPHTTPSessionIntervalResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetBIPHTTPSessionIntervalResponse")
  @RequestWrapper(localName="getBIPHTTPSessionInterval", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetBIPHTTPSessionInterval")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getBIPHTTPSessionIntervalReturn")
  public int getBIPHTTPSessionInterval();

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/runReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/runReport/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/runReport/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/runReport/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/runReportResponse")
  @ResponseWrapper(localName="runReportResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.RunReportResponse")
  @RequestWrapper(localName="runReport", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.RunReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="runReportReturn")
  public com.oracle.xmlns.oxp.service.publicreportservice.ReportResponse runReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportRequest")
    com.oracle.xmlns.oxp.service.publicreportservice.ReportRequest reportRequest,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="appParams")
    String appParams)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportDefinitionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportDefinition/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportDefinition/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportDefinition/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportDefinitionResponse")
  @ResponseWrapper(localName="getReportDefinitionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetReportDefinitionResponse")
  @RequestWrapper(localName="getReportDefinition", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetReportDefinition")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getReportDefinitionReturn")
  public com.oracle.xmlns.oxp.service.publicreportservice.ReportDefinition getReportDefinition(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplate/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplate/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplate/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateResponse")
  @ResponseWrapper(localName="getTemplateResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetTemplateResponse")
  @RequestWrapper(localName="getTemplate", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetTemplate")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getTemplateReturn")
  public byte[] getTemplate(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateID")
    String templateID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="locale")
    String locale)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportSampleDataRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportSampleData/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportSampleData/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportSampleData/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportSampleDataResponse")
  @ResponseWrapper(localName="getReportSampleDataResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetReportSampleDataResponse")
  @RequestWrapper(localName="getReportSampleData", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetReportSampleData")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getReportSampleDataReturn")
  public byte[] getReportSampleData(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getXDOSchemaRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getXDOSchema/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getXDOSchema/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getXDOSchema/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getXDOSchemaResponse")
  @ResponseWrapper(localName="getXDOSchemaResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetXDOSchemaResponse")
  @RequestWrapper(localName="getXDOSchema", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetXDOSchema")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getXDOSchemaReturn")
  public byte[] getXDOSchema(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="locale")
    String locale)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportParametersRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportParameters/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportParameters/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportParameters/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportParametersResponse")
  @ResponseWrapper(localName="getReportParametersResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetReportParametersResponse")
  @RequestWrapper(localName="getReportParameters", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetReportParameters")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getReportParametersReturn")
  public com.oracle.xmlns.oxp.service.publicreportservice.ParamNameValues getReportParameters(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportRequest")
    com.oracle.xmlns.oxp.service.publicreportservice.ReportRequest reportRequest)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateParametersRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateParameters/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateParameters/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateParameters/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateParametersResponse")
  @ResponseWrapper(localName="getTemplateParametersResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetTemplateParametersResponse")
  @RequestWrapper(localName="getTemplateParameters", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetTemplateParameters")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getTemplateParametersReturn")
  public List<com.oracle.xmlns.oxp.service.publicreportservice.ParamNameValue> getTemplateParameters(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateID")
    String templateID)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getFolderContentsRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getFolderContents/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getFolderContents/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getFolderContents/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getFolderContentsResponse")
  @ResponseWrapper(localName="getFolderContentsResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetFolderContentsResponse")
  @RequestWrapper(localName="getFolderContents", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetFolderContents")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getFolderContentsReturn")
  public com.oracle.xmlns.oxp.service.publicreportservice.CatalogContents getFolderContents(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="folderAbsolutePath")
    String folderAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getDeliveryServiceDefinitionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getDeliveryServiceDefinition/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getDeliveryServiceDefinitionResponse")
  @ResponseWrapper(localName="getDeliveryServiceDefinitionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetDeliveryServiceDefinitionResponse")
  @RequestWrapper(localName="getDeliveryServiceDefinition",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.GetDeliveryServiceDefinition")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="getDeliveryServiceDefinitionReturn")
  public com.oracle.xmlns.oxp.service.publicreportservice.DeliveryServiceDefinition getDeliveryServiceDefinition()
    throws com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deliveryServiceRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deliveryService/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deliveryService/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deliveryService/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deliveryServiceResponse")
  @ResponseWrapper(localName="deliveryServiceResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DeliveryServiceResponse")
  @RequestWrapper(localName="deliveryService", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DeliveryService")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="deliveryServiceReturn")
  public String deliveryService(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="deliveryRequest")
    com.oracle.xmlns.oxp.service.publicreportservice.DeliveryRequest deliveryRequest)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/validateLoginRequest",
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/validateLoginResponse")
  @ResponseWrapper(localName="validateLoginResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.ValidateLoginResponse")
  @RequestWrapper(localName="validateLogin", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.ValidateLogin")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="validateLoginReturn")
  public boolean validateLogin();

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/hasReportAccessRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/hasReportAccess/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/hasReportAccessResponse")
  @ResponseWrapper(localName="hasReportAccessResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.HasReportAccessResponse")
  @RequestWrapper(localName="hasReportAccess", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.HasReportAccess")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="hasReportAccessReturn")
  public boolean hasReportAccess(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isReportExistRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isReportExist/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isReportExistResponse")
  @ResponseWrapper(localName="isReportExistResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.IsReportExistResponse")
  @RequestWrapper(localName="isReportExist", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.IsReportExist")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="isReportExistReturn")
  public boolean isReportExist(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isFolderExistRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isFolderExist/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isFolderExistResponse")
  @ResponseWrapper(localName="isFolderExistResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.IsFolderExistResponse")
  @RequestWrapper(localName="isFolderExist", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.IsFolderExist")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="isFolderExistReturn")
  public boolean isFolderExist(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="folderAbsolutePath")
    String folderAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReport/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReport/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReport/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportResponse")
  @ResponseWrapper(localName="createReportResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.CreateReportResponse")
  @RequestWrapper(localName="createReport", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.CreateReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="createReportReturn")
  public String createReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportName")
    String reportName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="folderAbsolutePathURL")
    String folderAbsolutePathURL, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateFileName")
    String templateFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateData")
    byte[] templateData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="XLIFFFileName")
    String xliffFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="XLIFFData")
    byte[] xliffData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="updateFlag")
    boolean updateFlag)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateReportDefinitionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateReportDefinition/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateReportDefinition/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateReportDefinition/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateReportDefinitionResponse")
  @ResponseWrapper(localName="updateReportDefinitionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UpdateReportDefinitionResponse")
  @RequestWrapper(localName="updateReportDefinition", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UpdateReportDefinition")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="updateReportDefinitionReturn")
  public boolean updateReportDefinition(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsPath")
    String reportAbsPath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="newReportDefn")
    com.oracle.xmlns.oxp.service.publicreportservice.ReportDefinition newReportDefn)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportFolderRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportFolder/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportFolder/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportFolder/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportFolderResponse")
  @ResponseWrapper(localName="createReportFolderResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.CreateReportFolderResponse")
  @RequestWrapper(localName="createReportFolder", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.CreateReportFolder")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="createReportFolderReturn")
  public String createReportFolder(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="folderAbsolutePath")
    String folderAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadTemplateForReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadTemplateForReport/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadTemplateForReport/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadTemplateForReport/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadTemplateForReportResponse")
  @ResponseWrapper(localName="uploadTemplateForReportResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UploadTemplateForReportResponse")
  @RequestWrapper(localName="uploadTemplateForReport", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UploadTemplateForReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="uploadTemplateForReportReturn")
  public boolean uploadTemplateForReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateName")
    String templateName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateType")
    String templateType, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateData")
    byte[] templateData)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateTemplateForReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateTemplateForReport/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateTemplateForReport/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateTemplateForReport/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateTemplateForReportResponse")
  @ResponseWrapper(localName="updateTemplateForReportResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UpdateTemplateForReportResponse")
  @RequestWrapper(localName="updateTemplateForReport", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UpdateTemplateForReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="updateTemplateForReportReturn")
  public boolean updateTemplateForReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateName")
    String templateName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateData")
    byte[] templateData)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/removeTemplateForReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/removeTemplateForReport/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/removeTemplateForReport/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/removeTemplateForReport/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/removeTemplateForReportResponse")
  @ResponseWrapper(localName="removeTemplateForReportResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.RemoveTemplateForReportResponse")
  @RequestWrapper(localName="removeTemplateForReport", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.RemoveTemplateForReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="removeTemplateForReportReturn")
  public boolean removeTemplateForReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="templateFileName")
    String templateFileName)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportDataChunkRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportDataChunk/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportDataChunkResponse")
  @ResponseWrapper(localName="uploadReportDataChunkResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UploadReportDataChunkResponse")
  @RequestWrapper(localName="uploadReportDataChunk", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UploadReportDataChunk")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="uploadReportDataChunkReturn")
  public String uploadReportDataChunk(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="fileID")
    String fileID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportDataChunk")
    byte[] reportDataChunk, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportRawDataChunk")
    String reportRawDataChunk)
    throws com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportDataChunkRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportDataChunk/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportDataChunkResponse")
  @ResponseWrapper(localName="downloadReportDataChunkResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DownloadReportDataChunkResponse")
  @RequestWrapper(localName="downloadReportDataChunk", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DownloadReportDataChunk")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="downloadReportDataChunkReturn")
  public com.oracle.xmlns.oxp.service.publicreportservice.ReportDataChunk downloadReportDataChunk(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="fileID")
    String fileID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="beginIdx")
    long beginIdx, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="size")
    int size)
    throws com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportObjectRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportObject/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportObject/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportObject/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportObjectResponse")
  @ResponseWrapper(localName="uploadReportObjectResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UploadReportObjectResponse")
  @RequestWrapper(localName="uploadReportObject", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.UploadReportObject")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="uploadReportObjectReturn")
  public String uploadReportObject(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportObjectAbsolutePathURL")
    String reportObjectAbsolutePathURL, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="objectType")
    String objectType, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="objectZippedData")
    byte[] objectZippedData)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteReport/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteReport/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteReport/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteReportResponse")
  @ResponseWrapper(localName="deleteReportResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DeleteReportResponse")
  @RequestWrapper(localName="deleteReport", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DeleteReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="deleteReportReturn")
  public boolean deleteReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteFolderRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteFolder/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteFolder/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteFolder/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteFolderResponse")
  @ResponseWrapper(localName="deleteFolderResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DeleteFolderResponse")
  @RequestWrapper(localName="deleteFolder", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DeleteFolder")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="deleteFolderReturn")
  public boolean deleteFolder(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="folderAbsolutePath")
    String folderAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportObjectRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportObject/Fault/InvalidParametersException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportObject/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportObject/Fault/OperationFailedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportObjectResponse")
  @ResponseWrapper(localName="downloadReportObjectResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DownloadReportObjectResponse")
  @RequestWrapper(localName="downloadReportObject", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.DownloadReportObject")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="downloadReportObjectReturn")
  public byte[] downloadReportObject(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="reportAbsolutePath")
    String reportAbsolutePath)
    throws com.oracle.xmlns.oxp.service.publicreportservice.InvalidParametersException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.OperationFailedException_Exception;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/submitReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/submitReport/Fault/SchedulingException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.SchedulingException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/submitReport/Fault/AccessDeniedException",
          className=com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException.class) },
    output="http://xmlns.oracle.com/oxp/service/PublicReportService/PublicReportService/ExternalReportWSSService/submitReportResponse")
  @ResponseWrapper(localName="submitReportResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.SubmitReportResponse")
  @RequestWrapper(localName="submitReport", targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    className="com.oracle.xmlns.oxp.service.publicreportservice.SubmitReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
    name="submitReportReturn")
  public String submitReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="submitReportData")
    byte[] submitReportData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
      name="appParams")
    String appParams)
    throws com.oracle.xmlns.oxp.service.publicreportservice.SchedulingException_Exception, com.oracle.xmlns.oxp.service.publicreportservice.AccessDeniedException_Exception;
}
