package com.oracle.xmlns.oxp.service.publicreportservice;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

@WebServiceClient(wsdlLocation="https://eehx-test.bi.em3.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?WSDL",
  targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
  name="ExternalReportWSSService")
public class ExternalReportWSSService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.oracle.xmlns.oxp.service.publicreportservice.ExternalReportWSSService_Service");
      URL baseUrl =
        ExternalReportWSSService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ExternalReportWSSService_Service.class.getResource("https://eehx-test.bi.em3.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://eehx-test.bi.em3.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "https://eehx-test.bi.em3.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://eehx-test.bi.em3.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?WSDL",
          e);
    }
  }

  public ExternalReportWSSService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/oxp/service/PublicReportService",
                    "ExternalReportWSSService"));
  }

  public ExternalReportWSSService_Service(URL wsdlLocation,
                                          QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ExternalReportWSSService")
  public com.oracle.xmlns.oxp.service.publicreportservice.ExternalReportWSSService getExternalReportWSSService()
  {
    return (com.oracle.xmlns.oxp.service.publicreportservice.ExternalReportWSSService) super.getPort(new QName("http://xmlns.oracle.com/oxp/service/PublicReportService",
                                                                                                               "ExternalReportWSSService"),
                                                                                                     com.oracle.xmlns.oxp.service.publicreportservice.ExternalReportWSSService.class);
  }

  @WebEndpoint(name="ExternalReportWSSService")
  public com.oracle.xmlns.oxp.service.publicreportservice.ExternalReportWSSService getExternalReportWSSService(WebServiceFeature... features)
  {
    return (com.oracle.xmlns.oxp.service.publicreportservice.ExternalReportWSSService) super.getPort(new QName("http://xmlns.oracle.com/oxp/service/PublicReportService",
                                                                                                               "ExternalReportWSSService"),
                                                                                                     com.oracle.xmlns.oxp.service.publicreportservice.ExternalReportWSSService.class,
                                                                                                     features);
  }
}
