package com.oracle.xmlns.oxp.service.publicreportservice;

import javax.xml.ws.WebFault;

@WebFault(faultBean="com.oracle.xmlns.oxp.service.publicreportservice.SchedulingException",
  targetNamespace="http://xmlns.oracle.com/oxp/service/PublicReportService",
  name="SchedulingException")
public class SchedulingException_Exception
  extends Exception
{
  private com.oracle.xmlns.oxp.service.publicreportservice.SchedulingException faultInfo;

  public SchedulingException_Exception(String message,
                                       com.oracle.xmlns.oxp.service.publicreportservice.SchedulingException faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public SchedulingException_Exception(String message,
                                       com.oracle.xmlns.oxp.service.publicreportservice.SchedulingException faultInfo,
                                       Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public com.oracle.xmlns.oxp.service.publicreportservice.SchedulingException getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(com.oracle.xmlns.oxp.service.publicreportservice.SchedulingException faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)
