package com.fsa.model.am;

import com.fsa.model.vo.DedutionSetupVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 18 10:32:10 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for DedutionSetupVO1.
     * @return DedutionSetupVO1
     */
    public DedutionSetupVOImpl getDedutionSetupVO1() {
        return (DedutionSetupVOImpl)findViewObject("DedutionSetupVO1");
    }

    /**
     * Container's getter for IPCDeductionVO1.
     * @return IPCDeductionVO1
     */
    public ViewObjectImpl getIPCDeductionVO1() {
        return (ViewObjectImpl)findViewObject("IPCDeductionVO1");
    }

    /**
     * Container's getter for DeductionTypeLOV1.
     * @return DeductionTypeLOV1
     */
    public ViewObjectImpl getDeductionTypeLOV1() {
        return (ViewObjectImpl)findViewObject("DeductionTypeLOV1");
    }

    /**
     * Container's getter for DeductionByTypeVO1.
     * @return DeductionByTypeVO1
     */
    public ViewObjectImpl getDeductionByTypeVO1() {
        return (ViewObjectImpl)findViewObject("DeductionByTypeVO1");
    }
}
