package model.VO;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 27 11:38:42 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractHeaderVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Dummy {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getDummy();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setDummy((String)value);
            }
        }
        ,
        ContractType {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getContractType();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setContractType((String)value);
            }
        }
        ,
        StartDate {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getStartDate();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setStartDate((String)value);
            }
        }
        ,
        EndDate {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getEndDate();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setEndDate((String)value);
            }
        }
        ,
        Currency {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getCurrency();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        CurrencyCode {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getCurrencyCode();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setCurrencyCode((String)value);
            }
        }
        ,
        Description {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Status {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Version {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getVersion();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setVersion((String)value);
            }
        }
        ,
        AdvancePercent {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getAdvancePercent();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setAdvancePercent((String)value);
            }
        }
        ,
        RetentionPercent {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getRetentionPercent();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setRetentionPercent((String)value);
            }
        }
        ,
        Deduction {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getDeduction();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setDeduction((String)value);
            }
        }
        ,
        ContractNumber {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getContractNumber();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setContractNumber((String)value);
            }
        }
        ,
        ProjectNumber {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getProjectNumber();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setProjectNumber((String)value);
            }
        }
        ,
        ProjectName {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getProjectName();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setProjectName((String)value);
            }
        }
        ,
        PaymentTerms {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getPaymentTerms();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setPaymentTerms((String)value);
            }
        }
        ,
        Amount {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getAmount();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setAmount((String)value);
            }
        }
        ,
        PartyName {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getPartyName();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setPartyName((String)value);
            }
        }
        ,
        PartyNumber {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getPartyNumber();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setPartyNumber((String)value);
            }
        }
        ,
        SupplierSite {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getSupplierSite();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setSupplierSite((String)value);
            }
        }
        ,
        ContractHeaderVO1 {
            public Object get(ContractHeaderVORowImpl obj) {
                return obj.getContractHeaderVO1();
            }

            public void put(ContractHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ContractHeaderVORowImpl object);

        public abstract void put(ContractHeaderVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DUMMY = AttributesEnum.Dummy.index();
    public static final int CONTRACTTYPE = AttributesEnum.ContractType.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int ADVANCEPERCENT = AttributesEnum.AdvancePercent.index();
    public static final int RETENTIONPERCENT = AttributesEnum.RetentionPercent.index();
    public static final int DEDUCTION = AttributesEnum.Deduction.index();
    public static final int CONTRACTNUMBER = AttributesEnum.ContractNumber.index();
    public static final int PROJECTNUMBER = AttributesEnum.ProjectNumber.index();
    public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
    public static final int PAYMENTTERMS = AttributesEnum.PaymentTerms.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int PARTYNAME = AttributesEnum.PartyName.index();
    public static final int PARTYNUMBER = AttributesEnum.PartyNumber.index();
    public static final int SUPPLIERSITE = AttributesEnum.SupplierSite.index();
    public static final int CONTRACTHEADERVO1 = AttributesEnum.ContractHeaderVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ContractHeaderVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Dummy.
     * @return the Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dummy.
     * @param value value to set the  Dummy
     */
    public void setDummy(String value) {
        setAttributeInternal(DUMMY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContractType.
     * @return the ContractType
     */
    public String getContractType() {
        return (String) getAttributeInternal(CONTRACTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContractType.
     * @param value value to set the  ContractType
     */
    public void setContractType(String value) {
        setAttributeInternal(CONTRACTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StartDate.
     * @return the StartDate
     */
    public String getStartDate() {
        return (String) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StartDate.
     * @param value value to set the  StartDate
     */
    public void setStartDate(String value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EndDate.
     * @return the EndDate
     */
    public String getEndDate() {
        return (String) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EndDate.
     * @param value value to set the  EndDate
     */
    public void setEndDate(String value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Currency.
     * @param value value to set the  Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyCode.
     * @return the CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode.
     * @param value value to set the  CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Version.
     * @return the Version
     */
    public String getVersion() {
        return (String) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Version.
     * @param value value to set the  Version
     */
    public void setVersion(String value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AdvancePercent.
     * @return the AdvancePercent
     */
    public String getAdvancePercent() {
        return (String) getAttributeInternal(ADVANCEPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AdvancePercent.
     * @param value value to set the  AdvancePercent
     */
    public void setAdvancePercent(String value) {
        setAttributeInternal(ADVANCEPERCENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RetentionPercent.
     * @return the RetentionPercent
     */
    public String getRetentionPercent() {
        return (String) getAttributeInternal(RETENTIONPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RetentionPercent.
     * @param value value to set the  RetentionPercent
     */
    public void setRetentionPercent(String value) {
        setAttributeInternal(RETENTIONPERCENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Deduction.
     * @return the Deduction
     */
    public String getDeduction() {
        return (String) getAttributeInternal(DEDUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Deduction.
     * @param value value to set the  Deduction
     */
    public void setDeduction(String value) {
        setAttributeInternal(DEDUCTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContractNumber.
     * @return the ContractNumber
     */
    public String getContractNumber() {
        return (String) getAttributeInternal(CONTRACTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContractNumber.
     * @param value value to set the  ContractNumber
     */
    public void setContractNumber(String value) {
        setAttributeInternal(CONTRACTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectNumber.
     * @return the ProjectNumber
     */
    public String getProjectNumber() {
        return (String) getAttributeInternal(PROJECTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectNumber.
     * @param value value to set the  ProjectNumber
     */
    public void setProjectNumber(String value) {
        setAttributeInternal(PROJECTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectName.
     * @return the ProjectName
     */
    public String getProjectName() {
        return (String) getAttributeInternal(PROJECTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectName.
     * @param value value to set the  ProjectName
     */
    public void setProjectName(String value) {
        setAttributeInternal(PROJECTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentTerms.
     * @return the PaymentTerms
     */
    public String getPaymentTerms() {
        return (String) getAttributeInternal(PAYMENTTERMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentTerms.
     * @param value value to set the  PaymentTerms
     */
    public void setPaymentTerms(String value) {
        setAttributeInternal(PAYMENTTERMS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Amount.
     * @return the Amount
     */
    public String getAmount() {
        return (String) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Amount.
     * @param value value to set the  Amount
     */
    public void setAmount(String value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartyName.
     * @return the PartyName
     */
    public String getPartyName() {
        return (String) getAttributeInternal(PARTYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartyName.
     * @param value value to set the  PartyName
     */
    public void setPartyName(String value) {
        setAttributeInternal(PARTYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartyNumber.
     * @return the PartyNumber
     */
    public String getPartyNumber() {
        return (String) getAttributeInternal(PARTYNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartyNumber.
     * @param value value to set the  PartyNumber
     */
    public void setPartyNumber(String value) {
        setAttributeInternal(PARTYNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SupplierSite.
     * @return the SupplierSite
     */
    public String getSupplierSite() {
        return (String) getAttributeInternal(SUPPLIERSITE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SupplierSite.
     * @param value value to set the  SupplierSite
     */
    public void setSupplierSite(String value) {
        setAttributeInternal(SUPPLIERSITE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractHeaderVO1.
     */
    public RowSet getContractHeaderVO1() {
        return (RowSet)getAttributeInternal(CONTRACTHEADERVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
