package model.VO;

import java.sql.ResultSet;

import java.util.ArrayList;
import java.util.List;

import model.beans.ServiceClientImpl;

import model.pojo.ContractHeaderPOJO;

import model.pojo.DeductionNamePOJO;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 21 17:58:18 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractHeaderVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    private List<ContractHeaderPOJO> contractheaderlist =
        new ArrayList<ContractHeaderPOJO>();
    ServiceClientImpl sci;

    public ContractHeaderVOImpl() {
        sci = new ServiceClientImpl();
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        if (getch_parameterbind() == 1) {
            contractheaderlist =
                    sci.getContractHeader(getch_cntrctidbind(), getch_cntrctversionbind());
            System.out.println("contractheaderlist size : " + contractheaderlist.size());
            setFetchIndex(qc, 0);
            super.executeQueryForCollection(qc, params, noUserParams);
        }
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        return getFetchIndex(qc) < contractheaderlist.size();
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        int curIndex = getFetchIndex(qc);
        ContractHeaderVORowImpl contractheaderrow =
            (ContractHeaderVORowImpl)createNewRowForCollection(qc);
        contractheaderrow.setContractNumber(contractheaderlist.get(curIndex).getContractnumber());
        contractheaderrow.setContractType(contractheaderlist.get(curIndex).getContracttype());
        contractheaderrow.setStartDate(contractheaderlist.get(curIndex).getStartdate());
        contractheaderrow.setEndDate(contractheaderlist.get(curIndex).getEnddate());
        contractheaderrow.setCurrency(contractheaderlist.get(curIndex).getCurrency());
        contractheaderrow.setCurrencyCode(contractheaderlist.get(curIndex).getCurrencycode());
        contractheaderrow.setDescription(contractheaderlist.get(curIndex).getDescription());
        contractheaderrow.setStatus(contractheaderlist.get(curIndex).getStatus());
        contractheaderrow.setVersion(contractheaderlist.get(curIndex).getVersion());
        contractheaderrow.setAdvancePercent(contractheaderlist.get(curIndex).getAdvancepercent());
        contractheaderrow.setRetentionPercent(contractheaderlist.get(curIndex).getRetentionpercent());
        contractheaderrow.setDeduction(contractheaderlist.get(curIndex).getDeduction());
        contractheaderrow.setProjectNumber(contractheaderlist.get(curIndex).getProjectnumber());
        contractheaderrow.setProjectName(contractheaderlist.get(curIndex).getProjectname());
        contractheaderrow.setPaymentTerms(contractheaderlist.get(curIndex).getPaymenterms());
        contractheaderrow.setAmount(contractheaderlist.get(curIndex).getAmount());
        contractheaderrow.setPartyName(contractheaderlist.get(curIndex).getPartyname());
        contractheaderrow.setPartyNumber(contractheaderlist.get(curIndex).getPartynumber());
        contractheaderrow.setSupplierSite(contractheaderlist.get(curIndex).getSuppliersite());
        setFetchIndex(qc, curIndex + 1);
        return contractheaderrow;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    public long getCappedQueryHitCount(ViewRowSetImpl viewRowSetImpl,
                                       Row[] row, long l, long l2) {
        long value = super.getCappedQueryHitCount(viewRowSetImpl, row, l, l2);
        return value;
    }

    private void setFetchIndex(Object rowset, int index) {
        if (index == contractheaderlist.size()) {
            setFetchCompleteForCollection(rowset, true);
        }
        setUserDataForCollection(rowset, new Integer(index));
    }

    private int getFetchIndex(Object rowset) {
        int value = ((Integer)getUserDataForCollection(rowset)).intValue();
        return value;
    }

    /**
     * Returns the bind variable value for ch_parameterbind.
     * @return bind variable value for ch_parameterbind
     */
    public Integer getch_parameterbind() {
        return (Integer)getNamedWhereClauseParam("ch_parameterbind");
    }

    /**
     * Sets <code>value</code> for bind variable ch_parameterbind.
     * @param value value to bind as ch_parameterbind
     */
    public void setch_parameterbind(Integer value) {
        setNamedWhereClauseParam("ch_parameterbind", value);
    }

    /**
     * Returns the variable value for ch_cntrctidbind.
     * @return variable value for ch_cntrctidbind
     */
    public String getch_cntrctidbind() {
        return (String)ensureVariableManager().getVariableValue("ch_cntrctidbind");
    }

    /**
     * Sets <code>value</code> for variable ch_cntrctidbind.
     * @param value value to bind as ch_cntrctidbind
     */
    public void setch_cntrctidbind(String value) {
        ensureVariableManager().setVariableValue("ch_cntrctidbind", value);
    }

    /**
     * Returns the variable value for ch_cntrctversionbind.
     * @return variable value for ch_cntrctversionbind
     */
    public String getch_cntrctversionbind() {
        return (String)ensureVariableManager().getVariableValue("ch_cntrctversionbind");
    }

    /**
     * Sets <code>value</code> for variable ch_cntrctversionbind.
     * @param value value to bind as ch_cntrctversionbind
     */
    public void setch_cntrctversionbind(String value) {
        ensureVariableManager().setVariableValue("ch_cntrctversionbind", value);
    }

    /**
     * Returns the variable value for ch_projectnumbind.
     * @return variable value for ch_projectnumbind
     */
    public String getch_projectnumbind() {
        return (String)ensureVariableManager().getVariableValue("ch_projectnumbind");
    }

    /**
     * Sets <code>value</code> for variable ch_projectnumbind.
     * @param value value to bind as ch_projectnumbind
     */
    public void setch_projectnumbind(String value) {
        ensureVariableManager().setVariableValue("ch_projectnumbind", value);
    }

    /**
     * Returns the variable value for ch_projectnamebind.
     * @return variable value for ch_projectnamebind
     */
    public String getch_projectnamebind() {
        return (String)ensureVariableManager().getVariableValue("ch_projectnamebind");
    }

    /**
     * Sets <code>value</code> for variable ch_projectnamebind.
     * @param value value to bind as ch_projectnamebind
     */
    public void setch_projectnamebind(String value) {
        ensureVariableManager().setVariableValue("ch_projectnamebind", value);
    }

    /**
     * Returns the bind variable value for ch_amountbind.
     * @return bind variable value for ch_amountbind
     */
    public String getch_amountbind() {
        return (String)getNamedWhereClauseParam("ch_amountbind");
    }

    /**
     * Sets <code>value</code> for bind variable ch_amountbind.
     * @param value value to bind as ch_amountbind
     */
    public void setch_amountbind(String value) {
        setNamedWhereClauseParam("ch_amountbind", value);
    }

    /**
     * Returns the bind variable value for ch_partynamebind.
     * @return bind variable value for ch_partynamebind
     */
    public String getch_partynamebind() {
        return (String)getNamedWhereClauseParam("ch_partynamebind");
    }

    /**
     * Sets <code>value</code> for bind variable ch_partynamebind.
     * @param value value to bind as ch_partynamebind
     */
    public void setch_partynamebind(String value) {
        setNamedWhereClauseParam("ch_partynamebind", value);
    }

    /**
     * Returns the variable value for ch_partynumberbind.
     * @return variable value for ch_partynumberbind
     */
    public String getch_partynumberbind() {
        return (String)ensureVariableManager().getVariableValue("ch_partynumberbind");
    }

    /**
     * Sets <code>value</code> for variable ch_partynumberbind.
     * @param value value to bind as ch_partynumberbind
     */
    public void setch_partynumberbind(String value) {
        ensureVariableManager().setVariableValue("ch_partynumberbind", value);
    }

    /**
     * Returns the variable value for ch_advancepaybind.
     * @return variable value for ch_advancepaybind
     */
    public String getch_advancepaybind() {
        return (String)ensureVariableManager().getVariableValue("ch_advancepaybind");
    }

    /**
     * Sets <code>value</code> for variable ch_advancepaybind.
     * @param value value to bind as ch_advancepaybind
     */
    public void setch_advancepaybind(String value) {
        ensureVariableManager().setVariableValue("ch_advancepaybind", value);
    }

    /**
     * Returns the variable value for ch_retentionbind.
     * @return variable value for ch_retentionbind
     */
    public String getch_retentionbind() {
        return (String)ensureVariableManager().getVariableValue("ch_retentionbind");
    }

    /**
     * Sets <code>value</code> for variable ch_retentionbind.
     * @param value value to bind as ch_retentionbind
     */
    public void setch_retentionbind(String value) {
        ensureVariableManager().setVariableValue("ch_retentionbind", value);
    }


    /**
     * Returns the variable value for ch_suppliersitebind.
     * @return variable value for ch_suppliersitebind
     */
    public String getch_suppliersitebind() {
        return (String)ensureVariableManager().getVariableValue("ch_suppliersitebind");
    }

    /**
     * Sets <code>value</code> for variable ch_suppliersitebind.
     * @param value value to bind as ch_suppliersitebind
     */
    public void setch_suppliersitebind(String value) {
        ensureVariableManager().setVariableValue("ch_suppliersitebind", value);
    }

    /**
     * Returns the variable value for ch_deductionenabledbind.
     * @return variable value for ch_deductionenabledbind
     */

    /**
     * Returns the variable value for ch_deductionenabledbind.
     * @return variable value for ch_deductionenabledbind
     */
    public String getch_deductionenabledbind() {
        return (String)ensureVariableManager().getVariableValue("ch_deductionenabledbind");
    }

    /**
     * Sets <code>value</code> for variable ch_deductionenabledbind.
     * @param value value to bind as ch_deductionenabledbind
     */
    public void setch_deductionenabledbind(String value) {
        ensureVariableManager().setVariableValue("ch_deductionenabledbind", value);
    }
}
