package model.VO;

import java.sql.ResultSet;

import java.util.ArrayList;
import java.util.List;

import model.beans.ServiceClientImpl;

import model.pojo.DeductionNamePOJO;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 18 14:09:45 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeductionNameVOImpl extends ViewObjectImpl {

    public DeductionNameVOImpl() {

    }
    private List<DeductionNamePOJO> deductionnamelist =
        new ArrayList<DeductionNamePOJO>();

    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        //Initialize Records here
        deductionnamelist.add(new DeductionNamePOJO("SC1"));
        deductionnamelist.add(new DeductionNamePOJO("SC2"));
        deductionnamelist.add(new DeductionNamePOJO("SC3"));
        deductionnamelist.add(new DeductionNamePOJO("SC4"));
        deductionnamelist.add(new DeductionNamePOJO("SC5"));
        //Set Initial fetch index to 0
        setFetchIndex(qc, 0);
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    protected boolean hasNextForCollection(Object qc) {
        // Check that there is other records to fetch from ArrayList
        return getFetchIndex(qc) < deductionnamelist.size();
    }

    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        // Get the current fetch index
        int curIndex = getFetchIndex(qc);
        // Create a new row
        DeductionNameVORowImpl characterRow =
            (DeductionNameVORowImpl)createNewRowForCollection(qc);
        //Here set attribute values in new row using RowImpl class
        characterRow.setDeductionName(deductionnamelist.get(curIndex).getDeductionname());
        // Change the fetch index as one record is increased in result set
        setFetchIndex(qc, curIndex + 1);
        // Return the newly created row
        return characterRow;
    }


    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    public long getCappedQueryHitCount(ViewRowSetImpl viewRowSet,
                                       Row[] masterRows, long oldCap,
                                       long cap) {
        long value =
            super.getCappedQueryHitCount(viewRowSet, masterRows, oldCap, cap);
        return value;
    }


    private void setFetchIndex(Object rowset, int index) {
        if (index == deductionnamelist.size()) {
            setFetchCompleteForCollection(rowset, true);
        }
        setUserDataForCollection(rowset, new Integer(index));
    }


    private int getFetchIndex(Object rowset) {
        int value = ((Integer)getUserDataForCollection(rowset)).intValue();
        return value;
    }
}
