package model.VO;

import java.sql.ResultSet;

import java.util.ArrayList;
import java.util.List;

import model.beans.ServiceClientImpl;

import model.pojo.ContractHeaderPOJO;

import model.pojo.DeductionNamePOJO;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 02 17:40:05 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobDeductionNameVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
     
     private List<DeductionNamePOJO> labourdeductionnamelist = 
         new ArrayList<DeductionNamePOJO>();
     ServiceClientImpl sci;
     
    public JobDeductionNameVOImpl() {
        
        sci = new ServiceClientImpl();
    }

    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
            labourdeductionnamelist = sci.getLabourDeductionNameDetails();
            setFetchIndex(qc, 0);
            super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        return getFetchIndex(qc) < labourdeductionnamelist.size();
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        int curIndex = getFetchIndex(qc);
        JobDeductionNameVORowImpl deductionnamerow =
            (JobDeductionNameVORowImpl)createNewRowForCollection(qc);
        deductionnamerow.setDeductionName(labourdeductionnamelist.get(curIndex).getDeductionname());
        setFetchIndex(qc, curIndex + 1);
        return deductionnamerow;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }
    public long getCappedQueryHitCount(ViewRowSetImpl viewRowSetImpl,
                                       Row[] row, long l, long l2) {
        long value = super.getCappedQueryHitCount(viewRowSetImpl, row, l, l2);
        return value;
    }

    private void setFetchIndex(Object rowset, int index) {
        if (index == labourdeductionnamelist.size()) {
            setFetchCompleteForCollection(rowset, true);
        }
        setUserDataForCollection(rowset, new Integer(index));
    }

    private int getFetchIndex(Object rowset) {
        int value = ((Integer)getUserDataForCollection(rowset)).intValue();
        return value;
    }
}
