package model.VO;

import java.sql.ResultSet;

import java.util.ArrayList;
import java.util.List;

import model.beans.ServiceClientImpl;

import model.pojo.ProjectDetailsPOJO;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 13:59:41 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProjectDetailsPVOImpl extends ViewObjectImpl {

    private List<ProjectDetailsPOJO> projectdetailslist =
        new ArrayList<ProjectDetailsPOJO>();
    ServiceClientImpl sci;

    public ProjectDetailsPVOImpl() {
        sci = new ServiceClientImpl();
    }

    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        if (getpd_parameterbind() == 1) {
            projectdetailslist = sci.getProjectDetails();
            setFetchIndex(qc, 0);
            super.executeQueryForCollection(qc, params, noUserParams);
        }
    }

    protected boolean hasNextForCollection(Object qc) {
        return getFetchIndex(qc) < projectdetailslist.size();
    }

    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        int curIndex = getFetchIndex(qc);
        ProjectDetailsPVORowImpl projectdetailsrow =
            (ProjectDetailsPVORowImpl)createNewRowForCollection(qc);
        projectdetailsrow.setProjectName(projectdetailslist.get(curIndex).getProjectname());
        projectdetailsrow.setProjectNumber(projectdetailslist.get(curIndex).getProjectnumber());
        setFetchIndex(qc, curIndex + 1);
        return projectdetailsrow;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    public long getCappedQueryHitCount(ViewRowSetImpl viewRowSetImpl,
                                       Row[] row, long l, long l2) {
        long value = super.getCappedQueryHitCount(viewRowSetImpl, row, l, l2);
        return value;
    }

    private void setFetchIndex(Object rowset, int index) {
        if (index == projectdetailslist.size()) {
            setFetchCompleteForCollection(rowset, true);
        }
        setUserDataForCollection(rowset, new Integer(index));
    }

    private int getFetchIndex(Object rowset) {
        int value = ((Integer)getUserDataForCollection(rowset)).intValue();
        return value;
    }

    public void setProjectdetailslist(List<ProjectDetailsPOJO> projectdetailslist) {
        this.projectdetailslist = projectdetailslist;
    }

    public List<ProjectDetailsPOJO> getProjectdetailslist() {
        return projectdetailslist;
    }

    /**
     * Returns the bind variable value for pd_parameterbind.
     * @return bind variable value for pd_parameterbind
     */
    public Integer getpd_parameterbind() {
        return (Integer)getNamedWhereClauseParam("pd_parameterbind");
    }

    /**
     * Sets <code>value</code> for bind variable pd_parameterbind.
     * @param value value to bind as pd_parameterbind
     */
    public void setpd_parameterbind(Integer value) {
        setNamedWhereClauseParam("pd_parameterbind", value);
    }

    /**
     * Returns the variable value for pd_projectnumberbind.
     * @return variable value for pd_projectnumberbind
     */
    public String getpd_projectnumberbind() {
        return (String)ensureVariableManager().getVariableValue("pd_projectnumberbind");
    }

    /**
     * Sets <code>value</code> for variable pd_projectnumberbind.
     * @param value value to bind as pd_projectnumberbind
     */
    public void setpd_projectnumberbind(String value) {
        ensureVariableManager().setVariableValue("pd_projectnumberbind",
                                                 value);
    }

}
