package model.AM;

import model.VO.ContractHeaderVOImpl;
import model.VO.ContractLineVOImpl;
import model.VO.ContractNumberVOImpl;

import model.VO.DeductionNameVOImpl;


import model.VO.JobDeductionNameVOImpl;
import model.VO.NonLaborResourcePVOImpl;
import model.VO.ProjectDetailsPVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 28 17:03:32 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for ContractHeaderVO1.
     * @return ContractHeaderVO1
     */
    public ContractHeaderVOImpl getContractHeaderVO1() {
        return (ContractHeaderVOImpl)findViewObject("ContractHeaderVO1");
    }

    /**
     * Container's getter for ContractLineVO1.
     * @return ContractLineVO1
     */
    public ContractLineVOImpl getContractLineVO1() {
        return (ContractLineVOImpl)findViewObject("ContractLineVO1");
    }

    /**
     * Container's getter for ContractNumberVO1.
     * @return ContractNumberVO1
     */
    public ContractNumberVOImpl getContractNumberVO1() {
        return (ContractNumberVOImpl)findViewObject("ContractNumberVO1");
    }

    /**
     * Container's getter for ContractNumberLovRVO1.
     * @return ContractNumberLovRVO1
     */
    public ViewObjectImpl getContractNumberLovRVO1() {
        return (ViewObjectImpl)findViewObject("ContractNumberLovRVO1");
    }


    /**
     * Container's getter for DeductionNameVO1.
     * @return DeductionNameVO1
     */
    public ViewObjectImpl getDeductionNameVO1() {
        return (ViewObjectImpl)findViewObject("DeductionNameVO1");
    }

    /**
     * Container's getter for DeductionNameLovRVO1.
     * @return DeductionNameLovRVO1
     */
    public ViewObjectImpl getDeductionNameLovRVO1() {
        return (ViewObjectImpl)findViewObject("DeductionNameLovRVO1");
    }

    /**
     * Container's getter for ProjectDetailsPVO1.
     * @return ProjectDetailsPVO1
     */
    public ProjectDetailsPVOImpl getProjectDetailsPVO1() {
        return (ProjectDetailsPVOImpl)findViewObject("ProjectDetailsPVO1");
    }

    /**
     * Container's getter for JobDeductionNameVO1.
     * @return JobDeductionNameVO1
     */
    public JobDeductionNameVOImpl getJobDeductionNameVO1() {
        return (JobDeductionNameVOImpl)findViewObject("JobDeductionNameVO1");
    }

    /**
     * Container's getter for NonLaborResourcePVO1.
     * @return NonLaborResourcePVO1
     */
    public NonLaborResourcePVOImpl getNonLaborResourcePVO1() {
        return (NonLaborResourcePVOImpl)findViewObject("NonLaborResourcePVO1");
    }

    /**
     * Container's getter for DedutionSetupVO1.
     * @return DedutionSetupVO1
     */
    public ViewObjectImpl getDedutionSetupVO1() {
        return (ViewObjectImpl)findViewObject("DedutionSetupVO1");
    }

    /**
     * Container's getter for IPCDeductionVO1.
     * @return IPCDeductionVO1
     */
    public ViewObjectImpl getIPCDeductionVO1() {
        return (ViewObjectImpl)findViewObject("IPCDeductionVO1");
    }

    /**
     * Container's getter for IPCDeductionAmountVO1.
     * @return IPCDeductionAmountVO1
     */
    public ViewObjectImpl getIPCDeductionAmountVO1() {
        return (ViewObjectImpl)findViewObject("IPCDeductionAmountVO1");
    }

    /**
     * Container's getter for DeductionByTypeVO1.
     * @return DeductionByTypeVO1
     */
    public ViewObjectImpl getDeductionByTypeVO1() {
        return (ViewObjectImpl)findViewObject("DeductionByTypeVO1");
    }
}
