package com.fsa.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 18 10:11:51 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DedutionSetupVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DedutionSetupVOImpl() {
    }

    /**
     * Returns the variable value for Bind_DeductionType.
     * @return variable value for Bind_DeductionType
     */
    public String getBind_DeductionType() {
        return (String)ensureVariableManager().getVariableValue("Bind_DeductionType");
    }

    /**
     * Sets <code>value</code> for variable Bind_DeductionType.
     * @param value value to bind as Bind_DeductionType
     */
    public void setBind_DeductionType(String value) {
        ensureVariableManager().setVariableValue("Bind_DeductionType", value);
    }
}
